apiVersion: v2
name: plumber
description: Helm chart for Plumber
type: application
version: "0.1.5"
appVersion: "0.1.5"
home: https://github.com/getplumber/platform/
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
  - name: gemini-jtff
    email: slongo@klanik.com
  - name: thomasboni
    email: thomas@getplumber.io
  - name: Totara-thib
    email: thibaud@getplumber.io
